# Generated by Django 4.0.4 on 2022-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timelapse_in_min', models.IntegerField()),
                ('cubic_per_meter', models.FloatField()),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timelapse_in_min', models.IntegerField()),
                ('cubic_per_meter', models.FloatField()),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
