# Generated by Django 4.0.4 on 2022-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='timelapse_in_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consumption_history',
            name='timelapse_in_min',
            field=models.FloatField(),
        ),
    ]
