# Generated by Django 4.0.4 on 2022-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_consumption_timelapse_in_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consumption_history',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
