# Generated by Django 4.0.4 on 2022-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_consumption_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='peso_per_cu_m',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='consumption_history',
            name='peso_per_cu_m',
            field=models.FloatField(default=0.5),
        ),
    ]
