# Generated by Django 4.0.4 on 2022-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_consumption_peso_per_cu_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='timelapse_format',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumption_history',
            name='timelapse_format',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
