# Generated by Django 4.0.4 on 2022-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_consumption_timelapse_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price_per_cubic', models.FloatField()),
            ],
        ),
    ]
